# Generated by Django 4.2.6 on 2023-10-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='problem_health',
            field=models.ManyToManyField(related_name='problems', to='api.problemshealth'),
        ),
    ]
